# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libxml2

r_packages:
  - covr
  
r_github_packages:
  - forkonlp/presidentSpeechKr

after_success:
  - Rscript -e 'library(covr); codecov()'